# Docker build and push pipeline

trigger:
  - main

pool:
  name: Default

steps:
  # No login required
  # - task: Docker@2
  #   displayName: "Registry login"
  #   inputs:
  #     command: login
  #     containerRegistry: SteffsContainerRegistry

  - task: DockerCompose@0
    displayName: 'Build services'
    inputs:
      # dockerRegistryEndpoint: SteffsContainerRegistry
      containerregistrytype: 'Container Registry'
      dockerComposeFile: '../.docker/docker-compose.build.yml'
      action: 'Build services'
      qualifyImageNames: true
      additionalImageTags: '$(Build.BuildId)'
      includeSourceTags: true
      includeLatestTag: true

  - task: DockerCompose@0
    displayName: 'Push services'
    inputs:
      # dockerRegistryEndpoint: SteffsContainerRegistry
      containerregistrytype: 'Container Registry'
      dockerComposeFile: '../.docker/docker-compose.build.yml'
      action: 'Push services'
      qualifyImageNames: true
      additionalImageTags: '$(Build.BuildId)'
      includeSourceTags: true
      includeLatestTag: true
